alias: SoC Lampe Farbe v1.0.0
description: LED zeigt per Farbe den aktuellen SoC an
triggers:
  - entity_id: sensor.soc
    for: "00:00:10"
    trigger: state
conditions: []
actions:
  - variables:
      soc: "{{ states('sensor.soc') | float(0) }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ pv < 20 }}"
        sequence:
          - target:
              entity_id: light.entity
            action: light.turn_off
      - conditions:
          - condition: template
            value_template: "{{ soc >= 20 and soc < 50}}"
        sequence:
          - target:
              entity_id: light.entity
            data:
              brightness: 150
              hs_color:
                - 0
                - 100
            action: light.turn_on
      - conditions:
          - condition: template
            value_template: "{{ soc >= 50 and soc < 80 }}"
        sequence:
          - target:
              entity_id: light.entity
            data:
              brightness: 180
              hs_color:
                - 30
                - 100
            action: light.turn_on
      - conditions:
          - condition: template
            value_template: "{{ soc >= 80 and soc < 95 }}"
        sequence:
          - target:
              entity_id: light.entity
            data:
              brightness: 220
              hs_color:
                - 60
                - 100
            action: light.turn_on
      - conditions:
          - condition: template
            value_template: "{{ soc >= 95 }}"
        sequence:
          - target:
              entity_id: light.entity
            data:
              brightness: 255
              hs_color:
                - 120
                - 100
            action: light.turn_on
  - condition: template
    value_template: "{{ states('sensor.soc') not in ['unknown','unavailable'] }}"
mode: restart
